# Generated by Django 3.0.2 on 2021-06-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=50, verbose_name='薬品名')),
                ('detail', models.TextField(verbose_name='特徴')),
            ],
            options={
                'verbose_name_plural': '医薬品の特徴',
            },
        ),
    ]
